---

- name: Create libvirt config dir
  tags:
    - configure
    - libvirt
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    setype: "{{ item.setype | default('container_file_t') }}"
    owner: "{{ item.owner | default(ansible_user) }}"
    group: "{{ item.group | default(ansible_user) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop:
    - {"path": "/var/lib/openstack/config/libvirt"}
    - {"path": "/var/lib/openstack/config/containers"}
    - {'path': "/var/lib/nova"}
    - {"path": "/etc/tmpfiles.d/", "owner": "root", "group": "root"}
    - {"path": "/var/lib/edpm-config/firewall", "owner": "root", "group": "root"}

- name: Create container config dirs
  become: true
  tags:
    - configure
    - libvirt
  ansible.builtin.file:
    path: "/var/lib/openstack/config/libvirt/{{ item }}"
    state: directory
    setype: "{{ item.setype | default('container_file_t') }}"
    owner: "{{ item.owner | default(ansible_user) }}"
    group: "{{ item.group | default(ansible_user) }}"
    mode: "0755"
  loop: "{{ edpm_libvirt_containers }}"

- name: Render libvirt container config.json
  become: true
  tags:
    - configure
    - libvirt
  ansible.builtin.template:
    src: "{{ item }}/config.json.j2"
    dest: "/var/lib/openstack/config/libvirt/{{ item }}/config.json"
    setype: "container_file_t"
    mode: "0644"
  loop: "{{ edpm_libvirt_containers }}"
  notify:
    - Restart libvirt

- name: Render libvirt config files
  become: true
  tags:
    - configure
    - libvirt
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/var/lib/openstack/config/libvirt/{{ item.dest }}"
    setype: "container_file_t"
    mode: "0644"
  loop:
    - {"src": "libvirt_virtlogd/virtlogd.conf", "dest": "libvirt_virtlogd/virtlogd.conf"}
    - {"src": "libvirt_virtnodedevd/virtnodedevd.conf", "dest": "libvirt_virtnodedevd/virtnodedevd.conf"}
    - {"src": "libvirt_virtproxyd/virtproxyd.conf", "dest": "libvirt_virtproxyd/virtproxyd.conf"}
    - {"src": "libvirt_virtqemud/virtqemud.conf", "dest": "libvirt_virtqemud/virtqemud.conf"}
    - {"src": "libvirt_virtqemud/qemu.conf", "dest": "libvirt_virtqemud/qemu.conf"}
    - {"src": "libvirt_virtsecretd/virtsecretd.conf", "dest": "libvirt_virtsecretd/virtsecretd.conf"}
  notify:
    - Restart libvirt
